name: "Release to Marketplace"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    
    - name: "Setup NodeJS"
      uses: "actions/setup-node@v2.1.0"
      
    - name: "Install Dependencies"
      run: "npm install"

    - name: "Run Tests"
      run: "npm run test"

    - name: "Publish to Marketplace"
      uses: "sigma/vsce-publish-action@v0.0.2"
      with:
        vsce_token: ${{ secrets.VSCE_TOKEN }}
