name: "Run Tests"

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    
    - name: "Setup NodeJS"
      uses: "actions/setup-node@v2.1.0"
      
    - name: "Install Dependencies"
      run: "npm install"

    - name: "Run Tests"
      run: "npm run test"
